(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const canvas=$('scene'), overlay=$('overlay'), overlayText=$('overlayText'), startBtn=$('startBtn'), resumeBtn=$('resumeBtn'), savePill=$('savePill'), leftBtn=$('leftBtn'), jumpBtn=$('jumpBtn'), rightBtn=$('rightBtn'), scoreEl=$('score'), bestEl=$('best'), coinsEl=$('coins'), levelEl=$('level');
  if(!canvas||!overlay||!overlayText||!startBtn||!resumeBtn||!savePill||!leftBtn||!jumpBtn||!rightBtn||!scoreEl||!bestEl||!coinsEl||!levelEl||!window.DontStopSave)return;
  const LEVELS={1:['NORMAL',11,1.30],2:['SCHNELL',12.3,1.18],3:['HART',13.5,1.08],4:['EXTREM',14.7,.99],5:['CHAOS',16,.91],6:['TURBO',17.2,.85],7:['NERVEN',18.4,.80],8:['RISKANT',19.5,.75],9:['BRUTAL',20.5,.71],10:['MASTER',21.5,.67],11:['APEX',22.4,.63],12:['INSANE',23.3,.59],13:['NIGHTMARE',24.2,.56],14:['OVERLOAD',25,.53],15:['MERCILESS',25.8,.51],16:['GODLIKE',26.6,.49],17:['APOCALYPSE',27.4,.47],18:['IMPOSSIBLE',28.2,.45],19:['LEGEND',29,.43],20:['ULTIMATE',30,.41]};
  const laneX=[-2.35,0,2.35], clamp=(n,a,b)=>Math.max(a,Math.min(b,n)), fmt=n=>Math.max(0,Math.floor(Number(n)||0)).toLocaleString('de-DE');
  const gl=canvas.getContext('webgl',{antialias:true,alpha:false,powerPreference:'high-performance'});
  if(!gl){overlayText.textContent='3D wird von diesem Gerät nicht unterstützt.';return;}
  const V=`attribute vec3 p; attribute vec3 n; uniform mat4 m,v,pr; varying vec3 nn; void main(){nn=mat3(m)*n;gl_Position=pr*v*m*vec4(p,1.0);}`;
  const F=`precision mediump float; uniform vec3 c; varying vec3 nn; void main(){vec3 L=normalize(vec3(-.4,1,.5));float d=max(dot(normalize(nn),L),0.0);gl_FragColor=vec4(c*(.38+.62*d),1.0);}`;
  function shader(t,s){const x=gl.createShader(t);if(!x)throw Error('Shader');gl.shaderSource(x,s);gl.compileShader(x);if(!gl.getShaderParameter(x,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(x)||'Shader');return x;}
  const p=gl.createProgram();if(!p)throw Error('Programm');gl.attachShader(p,shader(gl.VERTEX_SHADER,V));gl.attachShader(p,shader(gl.FRAGMENT_SHADER,F));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p)||'Link');gl.useProgram(p);
  const cube=new Float32Array([-1,-1,-1,0,0,-1,1,-1,-1,0,0,-1,1,1,-1,0,0,-1,-1,1,-1,0,0,-1,-1,-1,1,0,0,1,1,-1,1,0,0,1,1,1,1,0,0,1,-1,1,1,0,0,1,-1,-1,-1,-1,0,0,-1,1,-1,-1,-1,0,0,-1,1,1,1,-1,0,0,1,-1,1,1,-1,0,0,1,-1,-1,-1,0,-1,0,1,-1,-1,0,-1,0,1,-1,1,0,-1,0,-1,-1,1,0,-1,0,-1,1,-1,0,1,0,1,1,-1,0,1,0,1,1,1,0,1,0,-1,1,1,0,1,0]);
  const idx=new Uint16Array([0,1,2,0,2,3,4,6,5,4,7,6,8,9,13,8,13,12,9,10,14,9,14,13,11,15,14,11,14,10,8,12,15,8,15,11]);
  const vb=gl.createBuffer(),ib=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,vb);gl.bufferData(gl.ARRAY_BUFFER,cube,gl.STATIC_DRAW);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,idx,gl.STATIC_DRAW);
  const lp=gl.getAttribLocation(p,'p'),ln=gl.getAttribLocation(p,'n');gl.enableVertexAttribArray(lp);gl.enableVertexAttribArray(ln);gl.vertexAttribPointer(lp,3,gl.FLOAT,false,24,0);gl.vertexAttribPointer(ln,3,gl.FLOAT,false,24,12);const um=gl.getUniformLocation(p,'m'),uv=gl.getUniformLocation(p,'v'),upr=gl.getUniformLocation(p,'pr'),uc=gl.getUniformLocation(p,'c');gl.enable(gl.DEPTH_TEST);
  const I=()=>new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);
  const mul=(a,b)=>{const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o};
  const tr=(x,y,z)=>{const m=I();m[12]=x;m[13]=y;m[14]=z;return m}; const sc=(x,y,z)=>{const m=I();m[0]=x;m[5]=y;m[10]=z;return m};
  const ry=a=>{const m=I(),c=Math.cos(a),s=Math.sin(a);m[0]=c;m[2]=-s;m[8]=s;m[10]=c;return m};
  const rx=a=>{const m=I(),c=Math.cos(a),s=Math.sin(a);m[5]=c;m[6]=s;m[9]=-s;m[10]=c;return m};
  const perspective=(f,a,n,z)=>{const q=1/Math.tan(f/2),nf=1/(n-z),m=new Float32Array(16);m[0]=q/a;m[5]=q;m[10]=(z+n)*nf;m[11]=-1;m[14]=2*z*n*nf;return m};
  const look=(e,t)=>{let zx=e[0]-t[0],zy=e[1]-t[1],zz=e[2]-t[2],l=Math.hypot(zx,zy,zz)||1;zx/=l;zy/=l;zz/=l;let xx=zz,xy=0,xz=-zx; l=Math.hypot(xx,xy,xz)||1;xx/=l;xz/=l;const yx=zy*xz-zz*xy,yy=zz*xx-zx*xz,yz=zx*xy-zy*xx,m=I();m[0]=xx;m[1]=yx;m[2]=zx;m[8]=xz;m[9]=yz;m[10]=zz;m[12]=-(xx*e[0]+xz*e[2]);m[13]=-(yx*e[0]+yy*e[1]+yz*e[2]);m[14]=-(zx*e[0]+zy*e[1]+zz*e[2]);return m};
  let state=window.DontStopSave.read(), lane=clamp(Number(state.progress?.lane??1),0,2), selected=clamp(Number(state.selectedLevel||1),1,20),running=false,over=false,score=0,coins=0,dodges=0,elapsed=0,jumpUntil=0,last=performance.now(),spawn=0,raf=0,objects=[],combo=0;
  function saveNow(){try{window.DontStopSave.set({selectedLevel:selected,coins:Number(state.coins||0)+coins,bestScore:Math.max(Number(state.bestScore||0),Math.floor(score)),bestTime:Math.max(Number(state.bestTime||0),elapsed),bestCombo:Math.max(Number(state.bestCombo||0),combo),statistics:{...(state.statistics||{}),totalRuns:Number(state.statistics?.totalRuns||0)+(over?1:0),totalTime:Number(state.statistics?.totalTime||0)+elapsed,totalDodges:Number(state.statistics?.totalDodges||0)+dodges},progress:{...(state.progress||{}),lane,activeRun:null}});state=window.DontStopSave.read();return true}catch{return false}}
  function hud(){const cfg=LEVELS[selected];scoreEl.textContent=fmt(score);bestEl.textContent=fmt(state.bestScore);coinsEl.textContent=fmt(Number(state.coins||0)+coins);levelEl.textContent=`${selected} • ${cfg[0]}`;}
  function start(resume=false){selected=clamp(Number(window.DontStopSave.read().selectedLevel||1),1,20);state=window.DontStopSave.read();if(resume&&state.progress?.activeRun){const r=state.progress.activeRun;score=Number(r.score)||0;coins=Number(r.runCoins)||0;dodges=Number(r.dodged)||0;elapsed=Number(r.elapsed)||0;lane=clamp(Number(r.lane),0,2);}else{score=0;coins=0;dodges=0;elapsed=0;combo=0;}running=true;over=false;overlay.classList.add('hidden');objects.forEach(o=>o.remove());objects=[];spawn=.55;last=performance.now();hud();frame(last)}
  function finish(){if(!running)return;running=false;over=true;cancelAnimationFrame(raf);state=window.DontStopSave.read();saveNow();overlay.classList.remove('hidden');startBtn.hidden=false;resumeBtn.hidden=!state.progress?.activeRun;overlayText.textContent=`Run beendet • Score ${fmt(score)} • +${fmt(coins)} Coins • Ausweichmanöver ${fmt(dodges)}`;hud();}
  function saveCheckpoint(){if(!running)return;const s=window.DontStopSave.read();window.DontStopSave.set({progress:{...(s.progress||{}),lane,activeRun:{score:Math.floor(score),elapsed,runCoins:coins,dodged,lane,selectedLevel:selected}}});state=window.DontStopSave.read();savePill.textContent='GESPEICHERT'}
  function actionLeft(){if(!running)return;lane=clamp(lane-1,0,2)} function actionRight(){if(!running)return;lane=clamp(lane+1,0,2)} function actionJump(){if(!running)return;jumpUntil=performance.now()+420}
  leftBtn.addEventListener('click',e=>{e.preventDefault();actionLeft()});rightBtn.addEventListener('click',e=>{e.preventDefault();actionRight()});jumpBtn.addEventListener('click',e=>{e.preventDefault();actionJump()});startBtn.addEventListener('click',e=>{e.preventDefault();start(false)});resumeBtn.addEventListener('click',e=>{e.preventDefault();start(true)});
  document.addEventListener('keydown',e=>{if(e.repeat)return;if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a')actionLeft();else if(e.key==='ArrowRight'||e.key.toLowerCase()==='d')actionRight();else if(e.key==='ArrowUp'||e.key.toLowerCase()==='w'||e.code==='Space'){e.preventDefault();actionJump()}});
  let sx=0,sy=0;canvas.addEventListener('touchstart',e=>{const t=e.changedTouches[0];sx=t.clientX;sy=t.clientY},{passive:true});canvas.addEventListener('touchend',e=>{const t=e.changedTouches[0],dx=t.clientX-sx,dy=t.clientY-sy;if(Math.abs(dx)>50&&Math.abs(dx)>Math.abs(dy))dx<0?actionLeft():actionRight();else if(dy<-40)actionJump()},{passive:true});
  function spawnVisual(){const el=document.createElement('div');el.className='ds-obstacle';el.innerHTML='<img alt="Hindernis">';const img=el.firstElementChild;img.src=['./assets/obstacle-car.svg','./assets/obstacle-barrier.svg','./assets/obstacle-construction.svg'][Math.floor(Math.random()*3)];const l=Math.floor(Math.random()*3);el.dataset.lane=l;document.querySelector('.game').appendChild(el);objects.push(el);return el}
  function setupVisual(){let old=document.getElementById('dsVisual');if(old)old.remove();const root=document.createElement('div');root.id='dsVisual';root.innerHTML='<div class="ds-road"></div><div class="ds-runner"><img alt="Runner" src="./assets/avatar-starter.svg"></div><div class="ds-shadow"></div>';document.querySelector('.game').insertBefore(root,canvas);const style=document.createElement('style');style.textContent=`#dsVisual{position:absolute;inset:0;z-index:1;pointer-events:none;overflow:hidden}#dsVisual .ds-road{position:absolute;inset:0;background-size:cover;background-position:center}#dsVisual .ds-road:after{content:"";position:absolute;inset:0;background:linear-gradient(180deg,rgba(5,8,15,.06),rgba(2,3,7,.48) 100%)}#dsVisual .ds-runner{position:absolute;z-index:5;left:50%;bottom:7%;width:min(170px,30vw);transform:translateX(-50%)}#dsVisual .ds-runner img{width:100%;display:block;filter:drop-shadow(0 18px 18px rgba(0,0,0,.5))}#dsVisual .ds-shadow{position:absolute;z-index:4;left:50%;bottom:6.2%;width:min(115px,22vw);height:18px;transform:translateX(-50%);border-radius:50%;background:rgba(0,0,0,.4);filter:blur(7px)}.ds-obstacle{position:absolute;z-index:4;left:50%;bottom:54%;width:min(190px,34vw);transform:translateX(-50%) scale(.2);transform-origin:50% 100%;will-change:left,bottom,transform}.ds-obstacle img{display:block;width:100%;filter:drop-shadow(0 16px 14px rgba(0,0,0,.4))}@media(min-width:760px){#dsVisual .ds-runner{width:185px}.ds-obstacle{width:220px}}`;document.head.appendChild(style);window.__dsVisual=root;return root}
  const visual=setupVisual(),road=visual.querySelector('.ds-road'),runner=visual.querySelector('.ds-runner'),shadow=visual.querySelector('.ds-shadow');
  function worldImage(){const w=window.DontStopSave.read().progression?.world||'city';road.style.backgroundImage=`url('./assets/world-${w==='night'?'night':w}.svg')`;runner.querySelector('img').src={starter:'./assets/avatar-starter.svg',speedster:'./assets/avatar-speed.svg',collector:'./assets/avatar-starter.svg',ninja:'./assets/avatar-elite.svg',robot:'./assets/avatar-armor.svg',void:'./assets/avatar-elite.svg'}[window.DontStopSave.read().progression?.character||'starter']||'./assets/avatar-starter.svg'}
  function frame(now){if(!running)return;const dt=Math.min(.045,Math.max(0,(now-last)/1000));last=now;elapsed+=dt;score+=dt*(8+selected*1.3);spawn-=dt;if(spawn<=0){const el=spawnVisual();spawn=Math.max(0.48,(LEVELS[selected]?.[2]||1.3)-selected*.025)}
    const jumping=performance.now()<jumpUntil, jump=jumping?1:0;const px=innerWidth*(.5+[-.09,0,.09][lane]);runner.style.left=`${px}px`;runner.style.transform=`translateX(-50%) translateY(${jump?-70:0}px)`;shadow.style.left=`${px}px`;shadow.style.transform=`translateX(-50%) scaleX(${jump?.7:1})`;shadow.style.opacity=jump?.45:.78;
    for(let i=objects.length-1;i>=0;i--){const el=objects[i],p=Number(el.dataset.p||0)+dt*(.42+selected*.012);el.dataset.p=p;const l=Number(el.dataset.lane||0);const laneOffset=[-.09,0,.09][l];const bottom=54-p*49;const scale=.2+p*1.15;el.style.left=`${innerWidth*(.5+laneOffset*(.55+p*.75))}px`;el.style.bottom=`${bottom}%`;el.style.transform=`translateX(-50%) scale(${scale})`;
      // Collision only when the obstacle is at the player's depth. A jump clears it.
      if(p>.86&&p<1.03&&l===lane&&!jumping){finish();return}
      if(p>=1){if(l!==lane||jumping){coins+=1;dodges+=1;combo+=1;if(combo>Number(state.bestCombo||0))state.bestCombo=combo;}el.remove();objects.splice(i,1)} }
    worldImage();if(Math.floor(elapsed)%5===0&&Math.floor(elapsed*10)%10===0)saveCheckpoint();hud();raf=requestAnimationFrame(frame)}
  worldImage();hud();
  const ar=state.progress?.activeRun;if(ar){resumeBtn.hidden=false;overlayText.textContent=`Run gespeichert • Score ${fmt(ar.score)} • ${fmt(ar.runCoins)} Coins`}
})();
